CQRS/Controllers/AnimalsController.cs
using CQRS.ApplicationLogic.CommandBus;
using CQRS.ApplicationLogic.Commands;
using CQRS.ApplicationLogic.Queries;
using CQRS.ApplicationLogic.QueryBus;
using CQRS.Model;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace CQRS.Controllers
{
    public class AnimalsController : Controller
    {
        private readonly ICommandBus _commandBus;
        private readonly IQueryBus _queryBus;

        public AnimalsController(ICommandBus commandBus, IQueryBus queryBus)
        {
            _commandBus = commandBus;
            _queryBus = queryBus;
        }

        [HttpPost]
        public ActionResult Create(CreateAnimalCommand command)
        {
            _commandBus.SendCommand(command);

            return new HttpStatusCodeResult(HttpStatusCode.Accepted);
        }

        [HttpGet]
        public ActionResult GetAll(GetAnimalsQuery query)
        {
            var result = _queryBus.Process<GetAnimalsQuery, IEnumerable<Animal>>(query);

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

CQRS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CQRS.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

CQRS/Views/Home/Index.cshtml
@model CQRS.Model.Animal

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>

    <script src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
            crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="jumbotron text-center text-info">
            <h2>
                CQRS Example
            </h2>
        </div>
        <div class="row">
            <div class="col-6">
                <h1>Add an animal</h1>
                <p id="addAnimalResult">
                </p>
                <form method="post" action="@Url.Action("Create", "Animals")" id="createAnimalForm">
                    <div class="form-group">
                        <label for="Name">Name</label>
                        <input type="text" class="form-control" name="Name">
                    </div>
                    <div class="form-group">
                        <label for="Age">Age</label>
                        <input type="number" class="form-control" name="Age">
                    </div>
                    <button id="createAnimal" type="button" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col-6">
                <h1>List of animals</h1>
                <button id="getAnimals" type="button" class="btn btn-primary">Load</button>
                <p id="getAnimalsResult">

                </p>
                <pre id="animals">
                </pre>
            </div>
        </div>
    </div>
</body>
</html>

<script type="text/javascript">
    $(function () {

        $('#createAnimal').click(function () {

            setCreateAnimalStatus('Submitting...');

            var frm = $('#createAnimalForm');

            $.ajax({
                type: frm.attr('method'),
                url: frm.attr('action'),
                data: frm.serialize(),
                success: function () {
                    setCreateAnimalStatus('Success!');
                }
            });
        });

        $('#getAnimals').click(function () {

            setGetAnimalsStatus('Loading...');

            $.ajax({
                type: 'get',
                url: '@Url.Action("GetAll", "Animals")',
                success: function (data) {
                    setGetAnimalsStatus('Success!');

                    $('#animals').html('');

                    if (data.length == 0) {
                        $('#animals').append('There are no animals!');
                    }
                    else {
                        data.forEach(function (d) {
                            $('#animals').append('Name: ' + d.Name + ', Age: ' + d.Age + "<br />");
                        });
                    }
                }
            });
        });
    });

    function setGetAnimalsStatus(status) {
        setStatus('p#getAnimalsResult', status);

    }

    function setCreateAnimalStatus(status) {
        setStatus('p#addAnimalResult', status);
    }

    function setStatus(id, status) {
        $(id).html(status);
    }
</script>